Deep Neural Network Model Design Using Assignment #2 IRIS Data

Import all the necessary libraries

In [84]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from tensorflow.keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Activation, Dropout, BatchNormalization, Dense
from tensorflow.keras.optimizers import SGD

Load Iris dataset which is classic dataset used for classification tasks. It consists of 150 samples of iris flowers, each with four features: sepal length, sepal width, petal length, and petal width. The samples are categorized into three species: Iris Setosa, Iris Versicolor, and Iris Virginica.

The feature data (X) and target labels (y) are extracted.

In [106]:
iris = load_iris() #same dataset to https://archive.ics.uci.edu/ml/datasets/iris)
X = iris.data
y = iris.target
print(X[::5])

[[5.1 3.5 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.7 1.5 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.  3.  1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.  3.2 1.2 0.2]
 [5.  3.5 1.3 0.3]
 [4.8 3.  1.4 0.3]
 [7.  3.2 4.7 1.4]
 [5.7 2.8 4.5 1.3]
 [5.  2.  3.5 1. ]
 [6.7 3.1 4.4 1.4]
 [5.9 3.2 4.8 1.8]
 [6.6 3.  4.4 1.4]
 [5.5 2.4 3.8 1.1]
 [6.  3.4 4.5 1.6]
 [5.5 2.6 4.4 1.2]
 [5.7 3.  4.2 1.2]
 [6.3 3.3 6.  2.5]
 [7.6 3.  6.6 2.1]
 [6.5 3.2 5.1 2. ]
 [6.4 3.2 5.3 2.3]
 [6.9 3.2 5.7 2.3]
 [7.2 3.2 6.  1.8]
 [7.4 2.8 6.1 1.9]
 [7.7 3.  6.1 2.3]
 [6.7 3.1 5.6 2.4]
 [6.7 3.  5.2 2.3]]


One-hot encode the target variable ot use in a neural network.


In [86]:
encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y.reshape(-1, 1))
print(y[:5])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [87]:
print(f'X shape: {X.shape}')
print(f'y shape: {y.shape}') 

X shape: (150, 4)
y shape: (150, 3)


Split the data into Train (60%), Validation (20%), and Test (20%) as instructed
First, data is split into 60-40 parts by train_test_split() function with random state of 42
Secondly, 40% data split in half for validation and testing.

In [88]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_valid, X_test, y_valid, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)


Standardize the features using StandardScaler.

In [89]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

Build the sequential model using tensorflow.keras.

In [90]:
model = Sequential()

Add the input layer and first hidden layer with BatchNormalization and Dropout

In [91]:
model.add(Dense(128, input_shape=(X_train.shape[1],), activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))

Second hidden layer with BatchNormalization and Dropout

In [92]:
model.add(Dense(64, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))

Third hidden layer

In [93]:
model.add(Dense(32, activation='relu'))

Output layer with Dense function with the number of classes and softmax

In [94]:
model.add(Dense(3, activation='softmax'))

SGD optimizer with a learning rate and momentum. Momentum helps to maintain direction and speed up the convergence by incorporating information from previous updates.

In [95]:
optimizer = SGD(learning_rate=0.01, momentum=0.9)

Compile the model with categorical_crossentropy as loss function and accuracy as categorical accuracy function

In [96]:
model.compile(optimizer=SGD(), loss='categorical_crossentropy', metrics=['accuracy'])


Print model summary

In [97]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_22 (Dense)            (None, 128)               640       
                                                                 
 batch_normalization_6 (Batc  (None, 128)              512       
 hNormalization)                                                 
                                                                 
 dropout_6 (Dropout)         (None, 128)               0         
                                                                 
 dense_23 (Dense)            (None, 64)                8256      
                                                                 
 batch_normalization_7 (Batc  (None, 64)               256       
 hNormalization)                                                 
                                                                 
 dropout_7 (Dropout)         (None, 64)               

Train the model on the training data with validation data as supervisied learning goes

In [104]:
history = model.fit(X_train, y_train, validation_data=(X_valid, y_valid), epochs=100, batch_size=32)

Epoch 1/100
3/3 [==============================] - 0s 37ms/step - loss: 0.1991 - accuracy: 0.9222 - val_loss: 0.0171 - val_accuracy: 1.0000
Epoch 2/100
3/3 [==============================] - 0s 18ms/step - loss: 0.1500 - accuracy: 0.9333 - val_loss: 0.0176 - val_accuracy: 1.0000
Epoch 3/100
3/3 [==============================] - 0s 28ms/step - loss: 0.1408 - accuracy: 0.9556 - val_loss: 0.0150 - val_accuracy: 1.0000
Epoch 4/100
3/3 [==============================] - 0s 16ms/step - loss: 0.1567 - accuracy: 0.9444 - val_loss: 0.0195 - val_accuracy: 1.0000
Epoch 5/100
3/3 [==============================] - 0s 16ms/step - loss: 0.0670 - accuracy: 0.9778 - val_loss: 0.0162 - val_accuracy: 1.0000
Epoch 6/100
3/3 [==============================] - 0s 17ms/step - loss: 0.0735 - accuracy: 0.9667 - val_loss: 0.0140 - val_accuracy: 1.0000
Epoch 7/100
3/3 [==============================] - 0s 15ms/step - loss: 0.0731 - accuracy: 0.9667 - val_loss: 0.0139 - val_accuracy: 1.0000
Epoch 8/100
3/3 [===

3/3 [==============================] - 0s 17ms/step - loss: 0.1199 - accuracy: 0.9444 - val_loss: 0.0108 - val_accuracy: 1.0000
Epoch 60/100
3/3 [==============================] - 0s 17ms/step - loss: 0.0860 - accuracy: 0.9556 - val_loss: 0.0107 - val_accuracy: 1.0000
Epoch 61/100
3/3 [==============================] - 0s 17ms/step - loss: 0.0767 - accuracy: 0.9889 - val_loss: 0.0109 - val_accuracy: 1.0000
Epoch 62/100
3/3 [==============================] - 0s 16ms/step - loss: 0.1290 - accuracy: 0.9667 - val_loss: 0.0110 - val_accuracy: 1.0000
Epoch 63/100
3/3 [==============================] - 0s 18ms/step - loss: 0.1172 - accuracy: 0.9667 - val_loss: 0.0091 - val_accuracy: 1.0000
Epoch 64/100
3/3 [==============================] - 0s 17ms/step - loss: 0.1309 - accuracy: 0.9556 - val_loss: 0.0109 - val_accuracy: 1.0000
Epoch 65/100
3/3 [==============================] - 0s 17ms/step - loss: 0.0842 - accuracy: 0.9889 - val_loss: 0.0114 - val_accuracy: 1.0000
Epoch 66/100
3/3 [========

Evaluate the model on the test data to see how well it works on unseen data

In [105]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss}, Test Accuracy: {test_accuracy}')

1/1 [==============================] - 0s 31ms/step - loss: 0.1177 - accuracy: 0.9667
Test Loss: 0.1177058145403862, Test Accuracy: 0.9666666388511658


Accuracy is pretty good, I think model does a fina job. When parameters of epochs and batch_size were changed to (200,32), (100, 64), no improvement showed. So, simple is better.