In [1]:
# import the packages we need for this assignment
from PIL import Image
import numpy as np

# open the test image
# Note: If you didn't launch Python from the same directory where you saved
#       the file, chipmunk.png, you'll need to provide the full path name as
#       the argument to Image.open
im = Image.open('chipmunk.png')

# display relevant Image class attributes: dimensions (width, height),
# pixel format and file format
print (im.size, im.mode, im.format)

# Note: PIL does not have a built-in image display tool.  Instead, principally
# for debugging, there's a show method which saves an image to a temporary file
# on disk and calls a platform dependent external display utility
# (the default being "xv" on unix, and the "Paint" program on Windows).

# display the image
im.show()

(750, 599) RGB JPEG


In [3]:
im.size

(750, 599)

In [7]:
im = im.convert('L')

In [8]:
im.show()

In [9]:
im2 = im.crop((280,150,430,300))

im2.save('chipmunk_head.png', 'PNG')

im2.show()

In [10]:
im2_arr = np.asarray(im2)

im2_arr

array([[ 55,  55,  55, ...,  57,  57,  56],
       [ 54,  54,  54, ...,  57,  56,  55],
       [ 55,  55,  55, ...,  60,  56,  58],
       ...,
       [101,  79, 103, ..., 115, 115, 129],
       [ 98,  83, 106, ..., 116, 117, 114],
       [ 97,  89, 109, ..., 113, 120, 102]], dtype=uint8)

In [11]:
avg = np.mean(im2_arr)
avg

125.47813333333333

In [12]:
im3_arr = im2_arr.copy()

In [13]:
for x in range(0, 150):
    for y in range(0,150):
        im3_arr[y,x] = min(im3_arr[y,x] + 50, 255)
im3_arr[:10, :10]

array([[105, 105, 105, 106, 108, 109, 109, 108, 106, 109],
       [104, 104, 104, 106, 107, 109, 108, 107, 105, 108],
       [105, 105, 105, 108, 111, 110, 106, 102, 106, 110],
       [105, 103, 103, 106, 110, 111, 110, 108, 105, 109],
       [110, 107, 105, 105, 107, 108, 108, 108, 105, 108],
       [109, 107, 104, 104, 105, 106, 106, 106, 106, 108],
       [ 99,  99, 100, 103, 106, 108, 108, 108, 107, 106],
       [ 97,  98, 100, 103, 104, 105, 104, 104, 105, 104],
       [101, 101, 102, 103, 102, 100,  99,  99, 102, 102],
       [ 99, 100, 101, 101, 101, 101, 101, 102,  98,  99]], dtype=uint8)

In [14]:
im3 = Image.fromarray(im3_arr)
im3.save('chipmunk_head_bright.png','PNG')
im3.show()

In [15]:
im4_array = im2_arr.copy()
im4_array

array([[ 55,  55,  55, ...,  57,  57,  56],
       [ 54,  54,  54, ...,  57,  56,  55],
       [ 55,  55,  55, ...,  60,  56,  58],
       ...,
       [101,  79, 103, ..., 115, 115, 129],
       [ 98,  83, 106, ..., 116, 117, 114],
       [ 97,  89, 109, ..., 113, 120, 102]], dtype=uint8)

In [16]:
im4_array = im4_array * 0.5
im4_array

array([[27.5, 27.5, 27.5, ..., 28.5, 28.5, 28. ],
       [27. , 27. , 27. , ..., 28.5, 28. , 27.5],
       [27.5, 27.5, 27.5, ..., 30. , 28. , 29. ],
       ...,
       [50.5, 39.5, 51.5, ..., 57.5, 57.5, 64.5],
       [49. , 41.5, 53. , ..., 58. , 58.5, 57. ],
       [48.5, 44.5, 54.5, ..., 56.5, 60. , 51. ]])

In [19]:
im4_array = im4_array.astype('uint8')
im4_array

array([[27, 27, 27, ..., 28, 28, 28],
       [27, 27, 27, ..., 28, 28, 27],
       [27, 27, 27, ..., 30, 28, 29],
       ...,
       [50, 39, 51, ..., 57, 57, 64],
       [49, 41, 53, ..., 58, 58, 57],
       [48, 44, 54, ..., 56, 60, 51]], dtype=uint8)

In [20]:
im4 = Image.fromarray(im4_array)
im4.save('chipmunk_head_dark.png','PNG')
im4.show()

In [24]:
grad = np.arange(0,256)
grad = np.tile(grad,[256,1])
grad

array([[  0,   1,   2, ..., 253, 254, 255],
       [  0,   1,   2, ..., 253, 254, 255],
       [  0,   1,   2, ..., 253, 254, 255],
       ...,
       [  0,   1,   2, ..., 253, 254, 255],
       [  0,   1,   2, ..., 253, 254, 255],
       [  0,   1,   2, ..., 253, 254, 255]])

In [ ]:
im5 = (Image.fromarray(grad.astype('uint8')))
im5.save('gradient.png','PNG')
im5.show()

In [25]:
grad.shape

(256, 256)